# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Sensors_Const.xdc

# Block Designs: bd/Sensors_ML/Sensors_ML.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Sensors_ML || ORIG_REF_NAME==Sensors_ML} -quiet] -quiet

# IP: bd/Sensors_ML/ip/Sensors_ML_PmodAD2_0_0/Sensors_ML_PmodAD2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Sensors_ML_PmodAD2_0_0 || ORIG_REF_NAME==Sensors_ML_PmodAD2_0_0} -quiet] -quiet

# IP: bd/Sensors_ML/ip/Sensors_ML_PmodTMP3_0_0/Sensors_ML_PmodTMP3_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Sensors_ML_PmodTMP3_0_0 || ORIG_REF_NAME==Sensors_ML_PmodTMP3_0_0} -quiet] -quiet

# IP: bd/Sensors_ML/ip/Sensors_ML_processing_system7_0_0/Sensors_ML_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Sensors_ML_processing_system7_0_0 || ORIG_REF_NAME==Sensors_ML_processing_system7_0_0} -quiet] -quiet

# IP: bd/Sensors_ML/ip/Sensors_ML_xbar_0/Sensors_ML_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Sensors_ML_xbar_0 || ORIG_REF_NAME==Sensors_ML_xbar_0} -quiet] -quiet

# IP: bd/Sensors_ML/ip/Sensors_ML_ps7_0_axi_periph_0/Sensors_ML_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Sensors_ML_ps7_0_axi_periph_0 || ORIG_REF_NAME==Sensors_ML_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Sensors_ML/ip/Sensors_ML_rst_ps7_0_50M_0/Sensors_ML_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Sensors_ML_rst_ps7_0_50M_0 || ORIG_REF_NAME==Sensors_ML_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/Sensors_ML/ip/Sensors_ML_xlconcat_0_0/Sensors_ML_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Sensors_ML_xlconcat_0_0 || ORIG_REF_NAME==Sensors_ML_xlconcat_0_0} -quiet] -quiet

# IP: bd/Sensors_ML/ip/Sensors_ML_SCORE_CALC_TOP_0_0/Sensors_ML_SCORE_CALC_TOP_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Sensors_ML_SCORE_CALC_TOP_0_0 || ORIG_REF_NAME==Sensors_ML_SCORE_CALC_TOP_0_0} -quiet] -quiet

# IP: bd/Sensors_ML/ip/Sensors_ML_axi_gpio_0_0/Sensors_ML_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Sensors_ML_axi_gpio_0_0 || ORIG_REF_NAME==Sensors_ML_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Sensors_ML/ip/Sensors_ML_axi_gpio_1_0/Sensors_ML_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Sensors_ML_axi_gpio_1_0 || ORIG_REF_NAME==Sensors_ML_axi_gpio_1_0} -quiet] -quiet

# IP: bd/Sensors_ML/ip/Sensors_ML_auto_pc_0/Sensors_ML_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Sensors_ML_auto_pc_0 || ORIG_REF_NAME==Sensors_ML_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/luisr/.Xilinx/VHDL_Projects/Graduate_Project/FPGA/Sensors_Machine_Learning/Sensors_Machine_Learning.gen/sources_1/bd/Sensors_ML/Sensors_ML_ooc.xdc
