# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/luisr/.Xilinx/VHDL_Projects/Graduate_Project/FPGA/Heart_Rate/Heart_Rate.srcs/sources_1/bd/BPM_DDR/ip/BPM_DDR_processing_system7_0_0/BPM_DDR_processing_system7_0_0.xci
# IP: The module: 'BPM_DDR_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/luisr/.Xilinx/VHDL_Projects/Graduate_Project/FPGA/Heart_Rate/Heart_Rate.gen/sources_1/bd/BPM_DDR/ip/BPM_DDR_processing_system7_0_0/BPM_DDR_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'BPM_DDR_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/luisr/.Xilinx/VHDL_Projects/Graduate_Project/FPGA/Heart_Rate/Heart_Rate.srcs/sources_1/bd/BPM_DDR/ip/BPM_DDR_processing_system7_0_0/BPM_DDR_processing_system7_0_0.xci
# IP: The module: 'BPM_DDR_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/luisr/.Xilinx/VHDL_Projects/Graduate_Project/FPGA/Heart_Rate/Heart_Rate.gen/sources_1/bd/BPM_DDR/ip/BPM_DDR_processing_system7_0_0/BPM_DDR_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'BPM_DDR_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
