# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/All_Sensors_Const.xdc

# Block Designs: bd/All_Sensors/All_Sensors.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==All_Sensors || ORIG_REF_NAME==All_Sensors} -quiet] -quiet

# IP: bd/All_Sensors/ip/All_Sensors_processing_system7_0_0/All_Sensors_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==All_Sensors_processing_system7_0_0 || ORIG_REF_NAME==All_Sensors_processing_system7_0_0} -quiet] -quiet

# IP: bd/All_Sensors/ip/All_Sensors_PmodTMP3_0_0/All_Sensors_PmodTMP3_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==All_Sensors_PmodTMP3_0_0 || ORIG_REF_NAME==All_Sensors_PmodTMP3_0_0} -quiet] -quiet

# IP: bd/All_Sensors/ip/All_Sensors_PmodAD2_0_0/All_Sensors_PmodAD2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==All_Sensors_PmodAD2_0_0 || ORIG_REF_NAME==All_Sensors_PmodAD2_0_0} -quiet] -quiet

# IP: bd/All_Sensors/ip/All_Sensors_xbar_0/All_Sensors_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==All_Sensors_xbar_0 || ORIG_REF_NAME==All_Sensors_xbar_0} -quiet] -quiet

# IP: bd/All_Sensors/ip/All_Sensors_auto_pc_0/All_Sensors_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==All_Sensors_auto_pc_0 || ORIG_REF_NAME==All_Sensors_auto_pc_0} -quiet] -quiet

# IP: bd/All_Sensors/ip/All_Sensors_ps7_0_axi_periph_0/All_Sensors_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==All_Sensors_ps7_0_axi_periph_0 || ORIG_REF_NAME==All_Sensors_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/All_Sensors/ip/All_Sensors_rst_ps7_0_50M_0/All_Sensors_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==All_Sensors_rst_ps7_0_50M_0 || ORIG_REF_NAME==All_Sensors_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/All_Sensors/ip/All_Sensors_xlconcat_0_0/All_Sensors_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==All_Sensors_xlconcat_0_0 || ORIG_REF_NAME==All_Sensors_xlconcat_0_0} -quiet] -quiet

# XDC: c:/Users/luisr/.Xilinx/VHDL_Projects/Graduate_Project/FPGA/All_Sensors/All_Sensors.gen/sources_1/bd/All_Sensors/All_Sensors_ooc.xdc
