# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Heart_Rate_Const.xdc

# Block Designs: bd/BPM_DDR/BPM_DDR.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BPM_DDR || ORIG_REF_NAME==BPM_DDR} -quiet] -quiet

# IP: bd/BPM_DDR/ip/BPM_DDR_PmodAD2_0_0/BPM_DDR_PmodAD2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BPM_DDR_PmodAD2_0_0 || ORIG_REF_NAME==BPM_DDR_PmodAD2_0_0} -quiet] -quiet

# IP: bd/BPM_DDR/ip/BPM_DDR_processing_system7_0_0/BPM_DDR_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BPM_DDR_processing_system7_0_0 || ORIG_REF_NAME==BPM_DDR_processing_system7_0_0} -quiet] -quiet

# IP: bd/BPM_DDR/ip/BPM_DDR_ps7_0_axi_periph_0/BPM_DDR_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BPM_DDR_ps7_0_axi_periph_0 || ORIG_REF_NAME==BPM_DDR_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/BPM_DDR/ip/BPM_DDR_rst_ps7_0_50M_0/BPM_DDR_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BPM_DDR_rst_ps7_0_50M_0 || ORIG_REF_NAME==BPM_DDR_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/BPM_DDR/ip/BPM_DDR_auto_pc_0/BPM_DDR_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BPM_DDR_auto_pc_0 || ORIG_REF_NAME==BPM_DDR_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/luisr/.Xilinx/VHDL_Projects/Graduate_Project/FPGA/Heart_Rate/Heart_Rate.gen/sources_1/bd/BPM_DDR/BPM_DDR_ooc.xdc
