# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/luisr/.Xilinx/VHDL_Projects/Graduate_Project/FPGA/Sensors_ML/Sensors_ML.srcs/sources_1/bd/Sensors_ML/ip/Sensors_ML_processing_system7_0_0/Sensors_ML_processing_system7_0_0.xci
# IP: The module: 'Sensors_ML_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/luisr/.Xilinx/VHDL_Projects/Graduate_Project/FPGA/Sensors_ML/Sensors_ML.gen/sources_1/bd/Sensors_ML/ip/Sensors_ML_processing_system7_0_0/Sensors_ML_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Sensors_ML_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/luisr/.Xilinx/VHDL_Projects/Graduate_Project/FPGA/Sensors_ML/Sensors_ML.srcs/sources_1/bd/Sensors_ML/ip/Sensors_ML_processing_system7_0_0/Sensors_ML_processing_system7_0_0.xci
# IP: The module: 'Sensors_ML_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/luisr/.Xilinx/VHDL_Projects/Graduate_Project/FPGA/Sensors_ML/Sensors_ML.gen/sources_1/bd/Sensors_ML/ip/Sensors_ML_processing_system7_0_0/Sensors_ML_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Sensors_ML_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
