# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/luisr/.Xilinx/VHDL_Projects/Graduate_Project/FPGA/All_Sensors/All_Sensors.srcs/sources_1/bd/All_Sensors/ip/All_Sensors_auto_pc_0/All_Sensors_auto_pc_0.xci
# IP: The module: 'All_Sensors_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/luisr/.Xilinx/VHDL_Projects/Graduate_Project/FPGA/All_Sensors/All_Sensors.gen/sources_1/bd/All_Sensors/ip/All_Sensors_auto_pc_0/All_Sensors_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'All_Sensors_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/luisr/.Xilinx/VHDL_Projects/Graduate_Project/FPGA/All_Sensors/All_Sensors.srcs/sources_1/bd/All_Sensors/ip/All_Sensors_auto_pc_0/All_Sensors_auto_pc_0.xci
# IP: The module: 'All_Sensors_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/luisr/.Xilinx/VHDL_Projects/Graduate_Project/FPGA/All_Sensors/All_Sensors.gen/sources_1/bd/All_Sensors/ip/All_Sensors_auto_pc_0/All_Sensors_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'All_Sensors_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
