# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/likea/Desktop/GradProject/github/FPGA-Code/Sensors/Vivado/All_Sensors/All_Sensors.srcs/sources_1/ip/axi_cdma_0/axi_cdma_0.xci
# IP: The module: 'axi_cdma_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/likea/Desktop/GradProject/github/FPGA-Code/Sensors/Vivado/All_Sensors/All_Sensors.gen/sources_1/ip/axi_cdma_0/axi_cdma_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_cdma_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/likea/Desktop/GradProject/github/FPGA-Code/Sensors/Vivado/All_Sensors/All_Sensors.gen/sources_1/ip/axi_cdma_0/axi_cdma_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_cdma_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/likea/Desktop/GradProject/github/FPGA-Code/Sensors/Vivado/All_Sensors/All_Sensors.srcs/sources_1/ip/axi_cdma_0/axi_cdma_0.xci
# IP: The module: 'axi_cdma_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/likea/Desktop/GradProject/github/FPGA-Code/Sensors/Vivado/All_Sensors/All_Sensors.gen/sources_1/ip/axi_cdma_0/axi_cdma_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_cdma_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/likea/Desktop/GradProject/github/FPGA-Code/Sensors/Vivado/All_Sensors/All_Sensors.gen/sources_1/ip/axi_cdma_0/axi_cdma_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_cdma_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
