# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/SPI_Const.xdc

# Block Designs: bd/SPI/SPI.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SPI || ORIG_REF_NAME==SPI} -quiet] -quiet

# IP: bd/SPI/ip/SPI_processing_system7_0_0/SPI_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SPI_processing_system7_0_0 || ORIG_REF_NAME==SPI_processing_system7_0_0} -quiet] -quiet

# XDC: c:/Users/luisr/.Xilinx/VHDL_Projects/Graduate_Project/FPGA/SPI/SPI.gen/sources_1/bd/SPI/SPI_ooc.xdc
