# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/TMP3_Cons.xdc

# Block Designs: bd/TMP3/TMP3.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TMP3 || ORIG_REF_NAME==TMP3} -quiet] -quiet

# IP: bd/TMP3/ip/TMP3_processing_system7_0_0/TMP3_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TMP3_processing_system7_0_0 || ORIG_REF_NAME==TMP3_processing_system7_0_0} -quiet] -quiet

# IP: bd/TMP3/ip/TMP3_PmodTMP3_0_0/TMP3_PmodTMP3_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TMP3_PmodTMP3_0_0 || ORIG_REF_NAME==TMP3_PmodTMP3_0_0} -quiet] -quiet

# IP: bd/TMP3/ip/TMP3_auto_pc_0/TMP3_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TMP3_auto_pc_0 || ORIG_REF_NAME==TMP3_auto_pc_0} -quiet] -quiet

# IP: bd/TMP3/ip/TMP3_ps7_0_axi_periph_0/TMP3_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TMP3_ps7_0_axi_periph_0 || ORIG_REF_NAME==TMP3_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/TMP3/ip/TMP3_rst_ps7_0_50M_0/TMP3_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TMP3_rst_ps7_0_50M_0 || ORIG_REF_NAME==TMP3_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: c:/Users/luisr/.Xilinx/VHDL_Projects/Graduate_Project/FPGA/TMP3/TMP3.gen/sources_1/bd/TMP3/TMP3_ooc.xdc
