set_property SRC_FILE_INFO {cfile:C:/Users/luisr/.Xilinx/VHDL_Projects/Graduate_Project/FPGA/SPI/SPI.srcs/constrs_1/imports/new/SPI_Const.xdc rfile:../../../SPI.srcs/constrs_1/imports/new/SPI_Const.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T14 [get_ports spi_sck]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T15 [get_ports spi_mosi]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P14 [get_ports spi_miso]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R14 [get_ports spi_cs]
